# Generated by Django 5.2.2 on 2026-08-08 21:03

import django.db.models.deletion
import gateway.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=gateway.models._uuid_pk, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.UUIDField(default=gateway.models._uuid_pk, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('all_day', models.BooleanField(default=False)),
                ('is_shared', models.BooleanField(default=False)),
                ('attendees', models.ManyToManyField(blank=True, related_name='attending_events', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='gateway.case')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.UUIDField(default=gateway.models._uuid_pk, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=512)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('storage_key', models.CharField(max_length=1024)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('chunk_count', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='gateway.case')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventReminder',
            fields=[
                ('id', models.UUIDField(default=gateway.models._uuid_pk, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('minutes_before', models.PositiveIntegerField(default=30)),
                ('method', models.CharField(choices=[('app', 'In-app'), ('email', 'Email')], default='app', max_length=16)),
                ('sent', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='gateway.calendarevent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LawFirm',
            fields=[
                ('id', models.UUIDField(default=gateway.models._uuid_pk, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_firms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='case',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='gateway.lawfirm'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='gateway.lawfirm'),
        ),
        migrations.CreateModel(
            name='AudioUpload',
            fields=[
                ('id', models.UUIDField(default=gateway.models._uuid_pk, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=512)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('storage_key', models.CharField(max_length=1024)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, default='', help_text='ISO code, or blank for auto-detect (multilingual).', max_length=16)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_uploads', to='gateway.case')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_uploads', to='gateway.lawfirm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.UUIDField(default=gateway.models._uuid_pk, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, default='')),
                ('detected_language', models.CharField(blank=True, default='', max_length=16)),
                ('segments', models.JSONField(blank=True, default=list)),
                ('provider', models.CharField(blank=True, default='', max_length=64)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='gateway.audioupload')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.UUIDField(default=gateway.models._uuid_pk, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('staff', 'Staff')], default='staff', max_length=16)),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='gateway.lawfirm')),
            ],
            options={
                'indexes': [models.Index(fields=['firm', 'email', 'status'], name='gateway_inv_firm_id_aebfdf_idx')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=gateway.models._uuid_pk, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('staff', 'Staff')], default='staff', max_length=16)),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='gateway.lawfirm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('firm', 'user')},
            },
        ),
    ]
