# Generated by Django 5.2.2 on 2026-08-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GmiSpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('input_tokens', models.BigIntegerField(default=0)),
                ('output_tokens', models.BigIntegerField(default=0)),
                ('usd_spent', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
            ],
            options={
                'ordering': ['-day'],
            },
        ),
    ]
